# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12WFEPZbJFuLtJGPXlpwi0frLOKE4136I
"""

'''
Calicia Perea
HW 1 
Machine Learning 
January 28, 2023
'''




#READ IN IRIS DATASET
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.lib.function_base import average

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML /hw1/iris.data.csv',header=None)


#CALCULATE NUMBER OF ROWS AND COLOUMNS DATASET CONTAINS
cols = len(df.columns)
row = len(df)
txt = "Number of Columns: {} "
txt2= "Number of Rows: {} " 
print(txt.format(cols))
print(txt2.format(row))

#GET ALL VALUES IN LAST COLUMN AND PRINT DISTINCT VALUES 
print(df[4].unique())

#IF “Iris-setosa” , CALCULATE NUMBER OF ROWS ,AVERAGE VALUE OF FIRST COLUMN
#MAX VALUE OF SECOND COLUMN, MIN OF THIRD
y= df.iloc[0:151,4].value_counts()['Iris-setosa']
print("Iris-setosa has count : ",y)

if y != False:
 average = sum(df[0])/ len(df[0])
 max = df[1].max()
 min = df[2].min()
 print("Average of 1st column:", round(average,1),
       "\nMax of 2nd column: ", max,
       "\nMinimum of 3rd column: ", min)

#DRAW SCATTER PLOT OF FIRST & SECOND COLUMN
# Y AXIS = 2ND COLUMN ;X AXIS 1ST COLUMN

x1=df.iloc[0:51,0]
y1=df.iloc[0:51,1]
plt.scatter(x1,y1, marker= 'o',c='tab:purple')

x2=df.iloc[51:101,0]
y2=df.iloc[51:101,1]
plt.scatter(x2,y2,marker= '^',c='tab:orange')

x3=df.iloc[101:151,0]
y3=df.iloc[101:151,1]
plt.scatter(x3,y3,marker= 'D',c='tab:green')


plt.xlabel('first column - x axis')
plt.ylabel('second column - y axis')
plt.legend(['Iris-setosa','Iris-versicolor','Iris-virginica'])
plt.show()

from google.colab import drive
drive.mount('/content/drive')